import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import SearchBar from '../components/SearchBar'
import IssuesData from "../components/IssuesData"
import React from 'react';
import { useState, useRef, useEffect } from 'react'
import Error from "../components/Error"

export default function Home() {
  let API = 'https://api.github.com/repos/georgipavlov89/homework/issues'


  const userRef = useRef(null)
  const repoRef = useRef(null)
  const ref = useRef({ userRef, repoRef })
  const [userName, setUserName] = useState('')

  const [repoName, setRepoName] = useState('')
  const [data, setData] = useState('')
  const [isLoading, setLoading] = useState(false)


  function handleClick(e) {
    e.preventDefault()
    setUserName(userRef.current.value)
    setRepoName(repoRef.current.value)

  }


  useEffect(() => {
    setLoading(true)

    if (userName && repoName) {
      API = `https://api.github.com/repos/${userName}/${repoName}/issues`
    }

    fetch(API)
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
        setUserName(userRef.current.value)
        setRepoName(repoRef.current.value)
      })

  }, [userName, repoName])


  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Github Issues Tracker
        </h1>



        <div >

        </div>

      </main>
      <SearchBar
        userName={userName}
        repoName={repoName}
        handleClick={handleClick}
        userRef={userRef}
        repoRef={repoRef}

      />
      {
        isLoading ? <Error /> : <IssuesData
          data={data}
        />
      }

      <Error />
    </div>
  )
}
